#!/bin/bash

#####
# How to use
# ./get-security-group-ids | grep <security-group-name>
####

aws ec2 describe-security-groups | jq '.SecurityGroups[] | .GroupName, .GroupId ' | sed 'N; s/^" /"/g ; s/ /-/g ; s/\n/ = / ; s/"//g'
